// Package render produces AmneziaWG configuration text. It supports both
// V1 and V2 protocol profiles, and renders interface-side ([Interface] +
// many [Peer] blocks) as well as client-side configs (single [Peer] for
// the server).
//
// The renderer NEVER includes SaveConfig=true: per the report, persistent
// state must live in the database, not in the runtime config file.
package render

import (
	"fmt"
	"sort"
	"strings"

	"github.com/awg-rest/awg-rest/internal/domain"
)

// Interface contains the data needed to render an [Interface] block.
type Interface struct {
	PrivateKey string
	Address    []string // CIDRs, e.g. ["10.90.0.1/24"]
	ListenPort int
	MTU        int
	DNS        []string
	PostUp     string
	PostDown   string
}

// PeerEntry is a single [Peer] block on the server side.
type PeerEntry struct {
	PublicKey    string
	PresharedKey string
	AllowedIPs   []string
	Endpoint     string
	Keepalive    int
	Comment      string // optional human-readable label as a # comment
}

// Server renders the full server configuration. Peers are deterministically
// ordered by public key so the rendered byte stream is content-addressable.
func Server(iface Interface, profile domain.ProtocolProfile, peers []PeerEntry) string {
	var b strings.Builder
	b.WriteString("# Generated by awg-rest. Do not edit by hand.\n")
	b.WriteString("[Interface]\n")
	for _, a := range iface.Address {
		fmt.Fprintf(&b, "Address = %s\n", a)
	}
	if iface.ListenPort > 0 {
		fmt.Fprintf(&b, "ListenPort = %d\n", iface.ListenPort)
	}
	if iface.PrivateKey != "" {
		fmt.Fprintf(&b, "PrivateKey = %s\n", iface.PrivateKey)
	}
	if iface.MTU > 0 {
		fmt.Fprintf(&b, "MTU = %d\n", iface.MTU)
	}
	if len(iface.DNS) > 0 {
		fmt.Fprintf(&b, "DNS = %s\n", strings.Join(iface.DNS, ", "))
	}
	if iface.PostUp != "" {
		fmt.Fprintf(&b, "PostUp = %s\n", iface.PostUp)
	}
	if iface.PostDown != "" {
		fmt.Fprintf(&b, "PostDown = %s\n", iface.PostDown)
	}
	writeProfile(&b, profile, false)

	sorted := append([]PeerEntry(nil), peers...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].PublicKey < sorted[j].PublicKey })

	for _, p := range sorted {
		b.WriteString("\n[Peer]\n")
		if p.Comment != "" {
			fmt.Fprintf(&b, "# %s\n", p.Comment)
		}
		fmt.Fprintf(&b, "PublicKey = %s\n", p.PublicKey)
		if p.PresharedKey != "" {
			fmt.Fprintf(&b, "PresharedKey = %s\n", p.PresharedKey)
		}
		if len(p.AllowedIPs) > 0 {
			fmt.Fprintf(&b, "AllowedIPs = %s\n", strings.Join(p.AllowedIPs, ", "))
		}
		if p.Endpoint != "" {
			fmt.Fprintf(&b, "Endpoint = %s\n", p.Endpoint)
		}
		if p.Keepalive > 0 {
			fmt.Fprintf(&b, "PersistentKeepalive = %d\n", p.Keepalive)
		}
	}
	return b.String()
}

// ClientArgs is the input for Client().
type ClientArgs struct {
	ClientPrivateKey string
	ClientAddress    []string // CIDRs assigned to the client (/32, /128)
	DNS              []string
	MTU              int

	ServerPublicKey string
	ServerEndpoint  string // host:port
	PresharedKey    string

	AllowedIPs []string // typically 0.0.0.0/0, ::/0
	Keepalive  int
}

// Client renders the AmneziaWG configuration delivered to the end-user device.
// It includes the protocol profile parameters so the client kernel module /
// amneziawg-go can negotiate properly with the server.
func Client(args ClientArgs, profile domain.ProtocolProfile) string {
	var b strings.Builder
	b.WriteString("[Interface]\n")
	if args.ClientPrivateKey != "" {
		fmt.Fprintf(&b, "PrivateKey = %s\n", args.ClientPrivateKey)
	}
	for _, a := range args.ClientAddress {
		fmt.Fprintf(&b, "Address = %s\n", a)
	}
	if len(args.DNS) > 0 {
		fmt.Fprintf(&b, "DNS = %s\n", strings.Join(args.DNS, ", "))
	}
	if args.MTU > 0 {
		fmt.Fprintf(&b, "MTU = %d\n", args.MTU)
	}
	writeProfile(&b, profile, true)

	b.WriteString("\n[Peer]\n")
	fmt.Fprintf(&b, "PublicKey = %s\n", args.ServerPublicKey)
	if args.PresharedKey != "" {
		fmt.Fprintf(&b, "PresharedKey = %s\n", args.PresharedKey)
	}
	allowed := args.AllowedIPs
	if len(allowed) == 0 {
		allowed = []string{"0.0.0.0/0", "::/0"}
	}
	fmt.Fprintf(&b, "AllowedIPs = %s\n", strings.Join(allowed, ", "))
	fmt.Fprintf(&b, "Endpoint = %s\n", args.ServerEndpoint)
	if args.Keepalive > 0 {
		fmt.Fprintf(&b, "PersistentKeepalive = %d\n", args.Keepalive)
	}
	return b.String()
}

func writeProfile(b *strings.Builder, p domain.ProtocolProfile, includeEmptySpecialJunk bool) {
	fmt.Fprintf(b, "Jc = %d\n", p.Jc)
	fmt.Fprintf(b, "Jmin = %d\n", p.Jmin)
	fmt.Fprintf(b, "Jmax = %d\n", p.Jmax)
	fmt.Fprintf(b, "S1 = %d\n", p.S1)
	fmt.Fprintf(b, "S2 = %d\n", p.S2)
	if p.IsV2() {
		fmt.Fprintf(b, "S3 = %d\n", p.S3)
		fmt.Fprintf(b, "S4 = %d\n", p.S4)
	}
	fmt.Fprintf(b, "H1 = %s\n", p.H1.String())
	fmt.Fprintf(b, "H2 = %s\n", p.H2.String())
	fmt.Fprintf(b, "H3 = %s\n", p.H3.String())
	fmt.Fprintf(b, "H4 = %s\n", p.H4.String())
	if p.IsV2() {
		writeSpecialJunk(b, "I1", p.I1, includeEmptySpecialJunk)
		writeSpecialJunk(b, "I2", p.I2, includeEmptySpecialJunk)
		writeSpecialJunk(b, "I3", p.I3, includeEmptySpecialJunk)
		writeSpecialJunk(b, "I4", p.I4, includeEmptySpecialJunk)
		writeSpecialJunk(b, "I5", p.I5, includeEmptySpecialJunk)
	}
}

func writeSpecialJunk(b *strings.Builder, key, value string, includeEmpty bool) {
	if value == "" && !includeEmpty {
		return
	}
	fmt.Fprintf(b, "%s = %s\n", key, value)
}
